[package]
name = "mand"
version = "0.1.0"
authors = ["Russell Bentley <russell.w.bentley@icloud.com>"]

[dependencies]
glium = { git = "https://github.com/ThermalSpan/glium" }
cgmath = "*"
num = "*"
num-complex = "*"
